---
dokku_version: 0.26.6
dokku_users:
  - name: '{{ vault_ansible_user }}'
    username: '{{ vault_ansible_user }}'
    ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
dokku_plugins:
  - name: clone
    url: https://github.com/crisward/dokku-clone.git
  - name: letsencrypt
    url: https://github.com/dokku/dokku-letsencrypt.git