---
project_tld: '{{vault_project_tld}}'
default_timezone: 'Europe/Rome'
docker_user: "1010"
docker_group: "1010"
users_group: "100"
media_user: '{{docker_user}}'
media_group: '{{docker_group}}'
mariadb_host: 'mariadb'
mariadb_port: '3306'
mariadb_root_user: "root"
mariadb_root_password: "{{vault_mariadb_root_password}}"
data_directory: "/mnt/data"
project_directory: "/home/docker"
permanent_cache_directory: "/mnt/data-1"
sonarr_apikey: "{{vault_sonarr_apikey}}"
radarr_apikey: "{{vault_radarr_apikey}}"
jackett_apikey: "{{vault_jackett_apikey}}"
photo_tld: 'photo.{{vault_domain_tld}}'
git_tld: 'git.{{vault_domain_tld}}'
jellyfin_tld: 'cinema.{{vault_project_tld}}'
fqdn_services: []

vscode_tld: 'ide.{{project_tld}}'
vscode_volumes:
  - "{{ project_directory }}:{{ project_directory }}"

ssh_key_public_codeserver: '{{vault_public_ssh_key}}'

omdb_apikey: '{{vault_omdb_apikey}}'

theme_park_default: 'space-gray'