---
- name: Install defaults packages
  package:
    name:
      - restic
    state: present
  tags: local-srv

- name: Set the Restic passoword file
  copy:
    content: "{{restic_password}}"
    dest: "/etc/restic_password_file"
    mode: u=rw
  tags: local-srv

- name: Check if the local backup directory exists
  stat:
    path: "{{restic_repos.local.location}}"
  register: local_backup_details
  tags: local-srv

- name: Set the restic associated init variable for local repository
  set_fact:
    restic_repos: "{{restic_repos|combine({'local' : {'init' : false }}, recursive=True)}}"
  when: local_backup_details.stat.exists and local_backup_details.stat.isdir
  tags: local-srv

- name: Set the restic associated init variable for remote repository
  set_fact:
    restic_repos: "{{restic_repos|combine({'remote' : {'init' : false }}, recursive=True)}}"
  when: local_backup_details.stat.exists and local_backup_details.stat.isdir
  tags: local-srv

- name: Debug
  debug:
    var: restic_repos.local.init
  tags: local-srv

# https://github.com/arillso/ansible.restic
- name: Configure backup with Restic
  include_role:
    name: arillso.restic
  tags: local-srv