---
- name: Deploy media services
  hosts: docker-internal
  become: yes 
  roles:
    - jackett
    - transmission
    - radarr
    - sonarr
    - jellyfin
    - bazarr
    - calibre-web
    - calibre    
    - headphones
    - sabnzbd
    - hydra

- name: Deploy external docker services
  hosts: docker-external
  become: yes
  roles:
    - tdarr

- name: Register DNS names in Mikrotik
  hosts: routeros
  tasks:
    - include_tasks: roles/mikrotik/tasks/add-dns-cname-entry.yml
      vars:
        dns_name: "{{fqdn_service}}"
        dns_cname: "{{vault_docker_host}}"
      loop: "{{ fqdn_services|flatten(levels=1) }}"