---

- name: Ensure Calibre directory exists
  file:
    path: /home/docker/calibre
    state: directory
    owner: '{{docker_user}}'
    group: '{{users_group}}'
  tags: calibre

- name: Ensure Calibre tree directories exists
  file:
    path: "{{project_directory}}/calibre/{{ item.dir }}"
    state: directory
    owner: '{{docker_user}}'
    group: '{{users_group}}'
  loop:
    - { dir: config }
  tags: calibre

- name: Create Calibre Docker Container
  community.docker.docker_container:
    name: calibre
    image: ghcr.io/linuxserver/calibre
    state: started
    pull: yes
    hostname: calibre
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    networks_cli_compatible: yes
    # published_ports:
    #   - 8070:8080 # Calibre desktop gui.
    #   - 8071:8081 # Calibre webserver gui.
    volumes:
      - "{{project_directory}}/calibre/config:/config"
      - /mnt/books:/books
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: '{{docker_user}}'
      PGID: '{{users_group}}'
      TZ: "{{default_timezone}}"
    labels:
      traefik.http.routers.calibre.entrypoints: "websecure"
      traefik.http.routers.calibre.tls: "true"
      traefik.http.routers.calibre.rule: "Host(`calibre.{{project_tld}}`)"
      traefik.http.routers.calibre.middlewares: "authelia@docker"
      traefik.http.routers.calibre.service: "calibre"
      traefik.http.routers.calibre.tls.certresolver: "dnsChallenge"
      traefik.http.services.calibre.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags: calibre

- name: Add FQDN to the list of services available for '{{project_tld}}'
  set_fact:
   fqdn_services: "{{ fqdn_services + [item] }}"
  with_items:
   - "calibre.{{project_tld}}"