---
- name: Ensure handbrake directory exists
  file:
    path: "{{project_directory}}/handbrake"
    state: directory
    owner: "{{docker_user}}"
    group: "{{users_group}}"
  tags: handbrake

- name: Ensure handbrake tree directories exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{docker_user}}"
    group: "{{users_group}}"
  loop:
    - "{{project_directory}}/handbrake/config"
    - "{{permanent_cache_directory}}/handbrake_output"
  tags: handbrake

- name: Start Handbrake
  community.docker.docker_container:
    name: handbrake
    image: jlesage/handbrake:dev-latest
    hostname: handbrake
    pull: yes
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: stopped
    groups:
      - 109
    devices:
      - "/dev/dri:/dev/dri"
    user: root:root
    volumes:
      - "{{project_directory}}/handbrake/config:/config:rw"
      - "{{permanent_cache_directory}}/handbrake_output:/output"
      - "{{permanent_cache_directory}}/torrent/completed:/watch"
    labels:
      traefik.http.routers.handbrake.entrypoints: "websecure"
      traefik.http.routers.handbrake.tls: "true"
      traefik.http.routers.handbrake.rule: "Host(`handbrake.{{project_tld}}`)"
      traefik.http.routers.handbrake.middlewares: "authelia@docker"
      traefik.http.routers.handbrake.service: "handbrake"
      traefik.http.services.handbrake.loadbalancer.server.port: "5800"
      traefik.http.routers.handbrake.tls.certresolver: "dnsChallenge"
      traefik.enable: "true"
    env:
      USER_ID: "{{docker_user}}"
      GROUP_ID: "{{users_group}}"
      TZ: "Europe/Rome"
  tags: handbrake


