---
# tasks file for users
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  tags: common-configuration

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags: common-configuration

- name: Ensure group "users" exists with correct gid
  ansible.builtin.group:
    name: users
    state: present
    gid: 100
  tags: common-configuration

- name: Ensure group "'{{vault_ansible_user_group}}'" exists with correct gid
  ansible.builtin.group:
    name: '{{vault_ansible_user}}'
    state: present
    gid: '{{vault_ansible_user_gid}}'
  tags: common-configuration

- name: Set the correct admin group for CentOS and Red Hat
  set_fact:
    admin_group: 'adm'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux'

- name: Set the correct admin group for Ubuntu and Debian
  set_fact:
    admin_group: 'sudo,render'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add the user '{{vault_ansible_user}}' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: '{{vault_ansible_user}}'
    comment: '{{vault_ansible_user}}'
    uid: '{{vault_ansible_user_uid}}'
    group: '{{vault_ansible_user_group}}'
    shell: /bin/zsh
    groups: "{{admin_group}},wheel,users"
    append: yes
    password: '{{ vault_ansible_user_password}}'
  tags: common-configuration

- name: Set authorized key for '{{vault_ansible_user}}'
  authorized_key:
    user: '{{vault_ansible_user}}'
    state: present
    key: '{{vault_public_ssh_key}}'
  tags: common-configuration