---
- name: Ensure Bazarr Directory Exist
  file:
    path: "{{project_directory}}/bazarr/config"
    state: directory
    owner: "{{docker_user}}"
    group: "{{users_group}}"
  tags: bazarr

- name: Ensure Bazarr Configuration Files Exist
  template:
    src: config.ini.j2
    dest: "{{project_directory}}/bazarr/config/config.ini"
  notify: restart bazarr
  tags: bazarr
  no_log: false

- name: Create Bazarr Docker Container
  community.general.docker_container:
    name: bazarr
    image: "linuxserver/bazarr:{{bazarr_version}}"
    pull: yes
    hostname: bazarr
    container_default_behavior: compatibility
    network_mode: default
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    memory: 512M
    memory_swap: 512M
    env:
      PUID: "{{docker_user}}"
      PGID: "{{users_group}}"
      TZ: "{{default_timezone}}"
    volumes:
      - "{{project_directory}}/bazarr:/config"
      - "{{data_directory}}/movies:/movies"
      - "{{data_directory}}/tv:/tv"
      - "{{data_directory}}/kids:/media/kids"
      - "{{data_directory}}/anime:/media/anime"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.{{project_tld}}`)"
      traefik.http.middlewares.bazarr_rewrite_theme.plugin.rewritebody.rewrites.regex: "</head>"
      traefik.http.middlewares.bazarr_rewrite_theme.plugin.rewritebody.rewrites.replacement: "<link rel=stylesheet type=text/css href=https://gilbn.github.io/theme.park/CSS/themes/bazarr/{{theme_park_default}}.css></head>"
      traefik.http.middlewares.bazarr-refer-header.headers.referrerPolicy: "strict-origin-when-cross-origin"
      traefik.http.routers.bazarr.middlewares: "bazarr-refer-header,bazarr_rewrite_theme"
      traefik.http.routers.bazarr.service: "bazarr"
      traefik.http.routers.bazarr.tls.certresolver: "dnsChallenge"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
      traefik.enable: "true"
  tags: bazarr
