---
# Github: https://hub.docker.com/r/minio/minio/
- name: Ensure minio config directory exists
  file:
    path: "{{project_directory}}/minio/config"
    state: directory
    owner: "{{docker_user}}"
    group: "{{users_group}}"
  tags: minio

- name: Start Minio
  community.docker.docker_container:
    name: overleaf
    hostname: overleaf
    pull: yes
    image: "minio/minio:{{minio_version}}"
    state: started
    restart_policy: unless-stopped
    network_mode: default
    networks_cli_compatible: yes
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{permanent_cache_directory}}/overleaf:/data:rw"
      - "{{project_directory}}/overleaf/config:/config:rw"
    labels:
      traefik.http.routers.overleaf.entrypoints: "websecure"
      traefik.http.routers.overleaf.tls: "true"
      traefik.http.routers.overleaf.rule: "Host(`overleaf.{{project_tld}}`)"
      traefik.http.routers.overleaf.middlewares: "authelia@docker"
      traefik.http.routers.overleaf.service: "overleaf"
      traefik.http.routers.overleaf.tls.certresolver: "dnsChallenge"
      traefik.http.services.overleaf.loadbalancer.server.port: "80"
      traefik.enable: "true"
    env:
      PUID: '{{docker_user}}'
      PGID: '{{users_group}}'
      TZ: "{{default_timezone}}"
  tags: overleaf

- name: Add FQDN to the list of services available for '{{project_tld}}'
set_fact:
 fqdn_services: "{{ fqdn_services + [item] }}"
with_items:
 - "overleaf.{{project_tld}}"
tags: overleaf