---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  
- name: Install additional packages available only on Ubuntu/Debian
  package:
    name:
      - magic-wormhole
      - nfs-common
      - restic
      - figlet
    state: present
  tags: common-configuration
