---
- name: Install defaults packages
  package:
    name:
      - vim
      - tmux
      - sudo
      - zsh
      - magic-wormhole
      - nfs-common
      - restic
      - git
      - figlet # Required by welcome
      - quota  # Required by welcome
      - nfs-common
    state: present
  tags: common-configuration
    
- include_tasks: welcome.yml

- include_tasks: mount-nfs.yml

- include_tasks: idmapd.yml
  when: idmapd_enabled