---

- name: Install message binary
  become: yes
  copy:
    src: welcome-message/welcome/bin/welcome
    dest: /usr/bin/welcome
    owner: root
    group: root
    mode: 0755
  tags: common-configuration

- name: grep and register
  shell: >
          egrep "^{{vault_ansible_user}}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Copy required message configuration
  synchronize:
    src: welcome-message/my-welcome/
    dest: '{{user_home.stdout}}/.welcome'
    delete: yes
    recursive: yes
  tags: common-configuration

- name: Ensure the welcome script is executed on login
  ansible.builtin.lineinfile:
    path: '{{user_home.stdout}}/.zshrc'
    regexp: '^Welcome script '
    insertafter: '^#Welcome '
    line: welcome